sudo: reguired
services:
    - docker 

before_install:
    - docker build -t sorin1333/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run 0e CI=true sorin1333/react-test npm test --coverage    

after_successs:
    - docker build -t sorin1333/multi-client ./client
    - docker build -t sorin1333/multi-nginx ./nginx
    - docker build -t sorin1333/multi-server ./server
    - docker build -t sorin1333/multi-worker ./worker
    # push to docker hub
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push sorin1333/multi-client
    - docker push sorin1333/multi-nginx
    - docker push sorin1333/multi-server
    - docker push sorin1333/multi-worker